#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com
#
# Updated to work in any project directory
#
# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
check_run() {
echo "$changed_files" | grep --quiet "$1" && cd ./$(git rev-parse --show-cdup) && cd $(change_dir "$1") && eval "$2"
}
change_dir() {
dirname $(find . -maxdepth 2 -mindepth 1 -name "$1" -type f | head -n 1)
}
# Example usage
# In this example it's used to run `npm install` if package.json changed and `bower install` if `bower.json` changed.
check_run package.json "npm install <% if (useJspm) { %>&& jspm install<% } %>"
check_run bower.json "bower install"
check_run composer.json "composer install"
