'use strict';
/**
 * creates critical path css for all html pages inside the .tmp folder generated by the html task.
 */
module.exports = {
    options: {
        base: '<%%= paths.dist %>',
        minify: true,
        css: ['.tmp/styles/main.css']
    },
    all: {
        files: [
            {expand: true, dot: true, cwd: '.tmp', dest: '<%%= paths.app %>/styles/critical/', src: ['**/*.html'], ext: '.css'}
        ]
    }
};
